version: '3.8'
services:
  redis:
    image: redis/redis-stack:7.4.0-v6
    container_name: redis
    ports:
      - "6379:6379"
      - "8001:8001"  # RedisInsight web UI port
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  redis_data:
    driver: local
